import nextCoreWebVitals from 'eslint-config-next/core-web-vitals'
import nextTypescript from 'eslint-config-next/typescript'

const eslintConfig = [
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    rules: {
      '@typescript-eslint/ban-ts-comment': 'warn',
      '@typescript-eslint/no-empty-object-type': 'warn',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          vars: 'all',
          args: 'after-used',
          ignoreRestSiblings: false,
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^(_|ignore)',
        },
      ],
    },
  },
  {
    // Payload-generated migrations: the CLI emits `up({ payload, req })` /
    // `down({ payload, req })` signatures with unused args on every
    // `migrate:create` — hand-editing them is churn that the next generation
    // reverts, so the unused-vars rule is off for this generated code only.
    files: ['src/migrations/**'],
    rules: {
      '@typescript-eslint/no-unused-vars': 'off',
    },
  },
  {
    ignores: [
      '**/.next/',
      '**/.open-next/',
      '.claude/',
      'packages/*/dist/',
      'public/widget/',
      'src/payload-types.ts',
      'src/payload-generated-schema.ts',
      // generated by `wrangler types`
      'cloudflare-env.d.ts',
    ],
  },
]

export default eslintConfig
